apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
data:
  opa.yaml: |
    discovery:
      name: discovery
      service: styra
    labels:
      system-id: f1d3f5b625664cfaa00a3404266757d5
      system-type: custom
    services:
    - name: styra
      url: https://slp:8443/v1
      tls:
        ca_cert: /certs/ca/ca.crt
      credentials:
        bearer:
          token: ${SLP_AUTHZ_TOKEN}
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  ports:
  - name: http
    port: 5000
    nodePort: 30050
  selector:
    app: demo
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-restful-api
        image: openpolicyagent/demo-restful-api:0.2
        ports:
        - containerPort: 5000
        env:
        - name: OPA_ADDR
          value: http://localhost:8181
        - name: POLICY_PATH
          value: /v1/data/httpapi/authz/main
      - name: opa
        image: "openpolicyagent/opa:0.48.0-rootless"
        args:
        - "run"
        - "--server"
        - "--config-file=/config/opa.yaml"
        env:
        - name: SLP_AUTHZ_TOKEN
          valueFrom:
            secretKeyRef:
              name: slp-authz-token
              key: token
        volumeMounts:
        - mountPath: /certs/ca
          name: ca-cert-vol
          readOnly: true
        - mountPath: /config
          name: opa-config-vol
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health?bundle=true
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: opa-config-vol
        configMap:
          name: opa-config
      - name: ca-cert-vol
        configMap:
          name: my-root-ca.crt
